version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/webapp"
    schedule:
      interval: "daily"
    assignees:
      - "Nivl"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Nivl"
