// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Health struct {
	Status string `json:"status"`
}

type PlaidLinkToken struct {
	Token string `json:"token"`
}

type PlaidPublicToken struct {
	Token string `json:"token"`
}
