import Head from 'next/head';

const FourOhFour = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>404 - Page Not Found</div>;
  </>
);

export default FourOhFour;
