version: "3"

tasks:
  build: go build -race -v -o ./bin/api github.com/Nivl/eista-api/cmd/api

  api-local-dev:
    deps: [build]
    cmds:
      - migrate -database $EISTA_POSTGRES_URL -path database/migrations up
      - ./bin/api
    sources:
      - ./**/*.go
      - go.mod

  start: docker-compose up --build

  lint: golangci-lint run ./...

  generate:
    cmds:
      - go get github.com/99designs/gqlgen/cmd
      - go generate ./...
      - go mod tidy

  deps-upgrade:
    cmds:
      - go get -t -u ./...
      - go mod tidy

  test: go test -race ./...
