version: "3"

dotenv: ['.env']

tasks:
  build: go build -race -v -o ./bin/api github.com/Nivl/eista-api/cmd/api

  api-local-dev:
    deps: [build]
    cmds:
      - ./bin/api
    sources:
      - ./**/*.go
      - go.mod

  start: docker-compose up --build

  migrate:
    cmds:
      - docker-compose exec api migrate -database ${EISTA_POSTGRES_URL} -path database/migrations {{.CMD}}
    vars:
      CMD: up


  lint: golangci-lint run ./...

  generate:
    cmds:
      - go get github.com/99designs/gqlgen/cmd
      - go generate ./...
      - go mod tidy

  deps-upgrade:
    cmds:
      - go get -t -u ./...
      - go mod tidy

  test: go test -race ./...
