name: webapp

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
    paths:
      - 'webapp/**'
      - '.github/**'
      - '!.github/workflows/api.yml'

defaults:
  run:
    working-directory: ./webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'yarn'
        cache-dependency-path: webapp/yarn.lock
    - run: yarn install --immutable

    - uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/webapp/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('webapp/yarn.lock') }}-${{ hashFiles('webapp/**.[jt]s', 'webapp/**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('webapp/yarn.lock') }}-
    - run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'yarn'
        cache-dependency-path: webapp/yarn.lock
    - run: yarn install
    - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'yarn'
        cache-dependency-path: webapp/yarn.lock
    - run: yarn install
    - run: yarn test

  e2e:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v3

    - run: cp .env.development .env

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: webapp
        command: yarn run test:e2e:ci --record
        start: yarn start
        build: yarn build
        wait-on: 'http://localhost:3000'
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-videos
        path: webapp/cypress/videos

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: webapp/cypress/screenshots

  build-storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'yarn'
        cache-dependency-path: webapp/yarn.lock
    - run: yarn install
    - run: yarn build-storybook

  chromatic-deployment:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # chromatic needs the full git history to run diffs

    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'yarn'
        cache-dependency-path: webapp/yarn.lock
    - run: yarn install
    - run: yarn build

    - name: Publish to Chromatic
      uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        workingDir: webapp
        exitZeroOnChanges: true
        autoAcceptChanges: main

