name: webapp

on:
  push:
    paths: # /!\ This will only trigger based on the _previous_ push
      - 'webapp/**'
      - '.github/**'
      - '!.github/workflows/api.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'webapp/**'
      - '.github/**'
      - '!.github/workflows/api.yml'

defaults:
  run:
    working-directory: ./webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - run: yarn install
    - run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - run: yarn install
    - run: yarn test

  e2e:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        install-command : yarn install
        command: yarn run test:e2e:ci
        build: yarn build
        start: yarn start
      env:
        # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
    # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos

  build-storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - run: yarn install
    - run: yarn build-storybook

  chromatic-deployment:
    runs-on: ubuntu-latest
    needs: [build, test, build-storybook]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # chromatic needs the full git history to run diffs
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - name: Fix until chromatic < 6 # https://github.com/chromaui/chromatic-cli/issues/166
      run: |
        sed -i 's/nodeLinker: pnp/nodeLinker: \"node-modules\"/' .yarnrc.yml
        yarn install
        yarn rebuild
        yarn build
    - name: Publish to Chromatic
      uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        workingDir: webapp
        exitZeroOnChanges: true
        autoAcceptChanges: main

