name: webapp

on: [push]
  #  push:
    # paths:
    #   - 'webapp/**'


defaults:
  run:
    working-directory: ./webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: yarn
        cache-dependency-path: webapp/yarn.lock
    - run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: yarn
        cache-dependency-path: webapp/yarn.lock
    - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: yarn
        cache-dependency-path: webapp/yarn.lock
    - run: yarn test

  build-storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: yarn
        cache-dependency-path: webapp/yarn.lock
    - run: yarn build-storybook

  chromatic-snapshots:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: yarn
        cache-dependency-path: webapp/yarn.lock
    - run: yarn chromatic
