name: webapp

on: [push]
   push:
    paths:
      - 'webapp/**'


defaults:
  run:
    working-directory: ./webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: yarn
        cache-dependency-path: webapp/yarn.lock
    - run: yarn install
    - run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: yarn
        cache-dependency-path: webapp/yarn.lock
    - run: yarn install
    - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: yarn
        cache-dependency-path: webapp/yarn.lock
    - run: yarn install
    - run: yarn test

  build-storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: yarn
        cache-dependency-path: webapp/yarn.lock
    - run: yarn install
    - run: yarn build-storybook

  chromatic-deployment:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: yarn
        cache-dependency-path: webapp/yarn.lock
    - run: yarn install
    - name: Publish to Chromatic
      uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        workingDir: webapp
        exitZeroOnChanges: true
        autoAcceptChanges: main

